name: Snaplet

inputs:
  database-create-command:
    description: Command used to generate the instant database
    required: false
    type: string
    default: snaplet database create --git --latest
  delete:
    description: Delete the database
    required: false
    type: boolean
    default: false
  database-delete-command:
    description: Command used to delete the instant database
    required: false
    type: string
    default: snaplet database delete --git
  database-url-command:
    description: Command used to get the instant database url
    required: false
    type: string
    default: snaplet database url --git
  reset-database-state:
    description: Reset the database state on each commit to the branch
    required: false
    type: boolean
    default: false

outputs:
  database-url:
    description: Instant database url
    value: ${{ steps.deploy.outputs.url }}

runs:
  using: composite
  steps:
    - name: Install Snaplet CLI
      shell: bash
      run: curl -sS "https://app.snaplet.dev/get-cli/" | bash &> "/dev/null"

    - if: ${{ inputs.delete == 'false' }}
      id: deploy
      name: Deploy Instant Database
      shell: bash
      run: |
        ${{ inputs.snaplet-database-url-command }} &> "/dev/null" || ${{ inputs.snaplet-database-create-command }}
        [ "${{ inputs.reset-database-state }}" == "true" ] && ${{ inputs.snaplet-database-create-command }}
        echo "::set-output name=database-url::$(${{ inputs.snaplet-database-url-command }})"

    - if: ${{ inputs.delete == 'true' }}
      name: Delete Instant Database
      shell: bash
      run: ${{ inputs.snaplet-database-delete-command }}

