name: Deploy

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - env:
          GIT_BRANCH: ${{ github.head_ref }}
          SNAPLET_ACCESS_TOKEN: ${{ secrets.SNAPLET_ACCESS_TOKEN }}
          SNAPLET_PROJECT_ID: ${{ secrets.SNAPLET_PROJECT_ID }}
          VERCEL_ACCESS_TOKEN: ${{ secrets.VERCEL_ACCESS_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: curl -sS "https://raw.githubusercontent.com/snaplet/vercel/main/scripts/deploy.sh" | bash